name: bst-project-actions
on: [push]


jobs:
  build_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build solution
        run: cd src && ghci BST.hs

  lint-tools:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Set up HLint'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: '3.1.6'

    - name: 'Run HLint'
      uses: rwe/actions-hlint-run@v2
      with:
        path: src/
        fail-on: warning

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test task
        run: stack test